FROM node:16.16-slim as build
WORKDIR /app
COPY ./clinical-trial-system .
RUN npm install --location=global yarn --force
RUN yarn install
RUN yarn build:prod

FROM nginx:1.23.0

RUN mkdir /app
WORKDIR /app
RUN mkdir ./build
COPY --from=build /app/dist ./build

RUN rm /etc/nginx/conf.d/default.conf
COPY ./Nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]