spring:
  profiles:
    include: oauth
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://root:0000@mysql:3306/BEAM-CTS?createDatabaseIfNotExist=true
#    username: root
#    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
hostLocation : localhost:3000
---
spring:
  datasource:
    url: jdbc:mysql://root:0000@localhost:3306/BEAM-CTS?createDatabaseIfNotExist=true
  config:
    activate:
      on-profile: dev
spring:
  datasource:
    url: jdbc:mysql://BEOKS:lee001409!@aa4hc4z4bbrpe.cdmqavurw4bt.ap-northeast-2.rds.amazonaws.com:3306/BEAM-CTS?createDatabaseIfNotExist=true
  config:
    activate:
      on-profile: prod
server:
  port: 5000 #for aws elastic beanstack
