package com.example.clinicaltrialsystem.ReviewResult.MLReviewResult

import org.springframework.data.repository.CrudRepository

interface MLReviewResultRepository : CrudRepository<MLReviewResult,MLReviewResultId>